### ISSUE TITLE
Bind failed for audio (port 5002) after docker build

### ISSUE THREAD

**Issue by 4563453** [flutterjanus/JanusDocker#2]
Hello, 
thank you very much for this docu. just run it. 
docker build -t dockerusername/janusgateway:latest .
docker run -d dockerusername/janusgateway:latest
started the container, docker exec janus bash
error message running janus 

[ERR] [plugins/janus_streaming.c:janus_streaming_create_fd:6451] [rtp-sample] Bind failed for audio (port 5002)... 98 (Address already in use)
[ERR] [plugins/janus_streaming.c:janus_streaming_create_rtp_source_stream:6643] [rtp-sample] Can't bind to port 5002...
[ERR] [plugins/janus_streaming.c:janus_streaming_init:2304] Skipping 'audio' stream 'rtp-sample', error creating source stream...
[ERR] [plugins/janus_streaming.c:janus_streaming_create_fd:6451] [multistream-test] Bind failed for audio (port 5102)... 98 (Address already in use)
[ERR] [plugins/janus_streaming.c:janus_streaming_create_rtp_source_stream:6643] [multistream-test] Can't bind to port 5102...
[ERR] [plugins/janus_streaming.c:janus_streaming_init:2116] Can't add 'audio' stream 'multistream-test', error creating source stream...

container is running with your docker-compose config
Any idea?

discord: R_M88#3664

**Comment by shivanshtalwar0** [comment]
This error means janus trying to use port 98 is already in use by some other process according to logs that you shared also it would better if you run this project using docker-compose rather than docker itself it will be far easier to manage
And yes the configs used in this Janus folder is what is utilised when container is built
